spring.application.name=variant-graph
server.port=8082

# H2 (local dev only)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
